### ISSUE TITLE
Running beautifully on Dell R520 (Flashed H710 IT Mode ) + 10GB Ethernet 

### ISSUE THREAD

**Issue by timmills** [Danielv123/serverManager#77]
Thanks thanks thanks - this just works!

I fiddled and nothing seemed to change - I exited the docker and restarted and it's now 100% adjusting perfectly.

It would be very cool to output to MQTT so that additional cooling/fan could be actioned.

**Comment by Danielv123** [comment]
There is no mqtt, but there is Prometheus support for data logging. Grafana supports automatic alerts etc if you want that, or you could just scrape the /metrics endpoint.

I have also noticed that sometimes changes don't apply until you restart, not sure what is going on. I haven't spent time to fix it because I haven't needed to touch anything since I made it

**Comment by timmills** [comment]
No problem and again thanks for your great work :)

This server is running xcp-ng do you know if there would be any way to
integrate H710 and the Intel 10GB temp sensors for monitoring?

**Comment by Danielv123** [comment]
Honestly no idea, if you got a cli command to read it with a relatively clean output I can look into adding it
